### ISSUE TITLE
How to append '+' at the end of number

### ISSUE THREAD

**Issue by smohdsalimansari** [talmand/jquery-animate-numbers#6]
I want to append '+' at the end of the animated number.

My code:
`TM_funfact: function() {
            var $animate_number = $('.animate-number');
            if( $animate_number.length > 0 ) {
                $animate_number.appear();
                $document_body.on('appear', '.animate-number', function() {
                    $animate_number.each(function() {
                        var current_item = $(this);
                        if (!current_item.hasClass('appeared')) {
                            current_item.animateNumbers(current_item.attr("data-value"), true, parseInt(current_item.attr("data-animation-duration"), 10)).addClass('appeared');														
                        }						
                    });
                });
            }
        },`

**Comment by talmand** [comment]
You can do something like this: http://jsfiddle.net/talmand/paj45r97/

I just added a parameter to the function that is expecting a string. In the step and complete methods of $.animate() you can append to the text. If you just want the the extra string to appear at the end of the animation then remove the if statement from the step method.
