### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hrieke** [talmand/jquery-animate-numbers#7]
Hi,

Under what license do you distribute your code under?
Thanks!

**Comment by talmand** [comment]
For this particular repo, feel free to use the code as you wish. If you'd like to point back to the repo in some way that would be nice, but up to you.

**Comment by hrieke** [comment]
Could you add this to the readme please?
Thanks!

**Comment by talmand** [comment]
I added a license file. Let me know if that helps you.
